<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>top.leafage</groupId>
        <artifactId>leafage-common</artifactId>
        <version>0.4.2</version>
    </parent>

    <artifactId>common-dependencies</artifactId>

    <name>common-data</name>
    <description>leafage common dependencies</description>
    <packaging>pom</packaging>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>top.leafage</groupId>
                <artifactId>common-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>top.leafage</groupId>
                <artifactId>common-data</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>top.leafage</groupId>
                <artifactId>common-data-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>top.leafage</groupId>
                <artifactId>common-data-jdbc</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>top.leafage</groupId>
                <artifactId>common-data-jpa</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>top.leafage</groupId>
                <artifactId>common-data-r2dbc</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>top.leafage</groupId>
                <artifactId>common-poi</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>top.leafage</groupId>
                <artifactId>common-logging</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>